# ConfigMap for Auth Microservice

apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
  namespace: auth-service
  labels:
    app.kubernetes.io/name:      auth-microservice
    app.kubernetes.io/component: config
data:
  PORT:            "3000"
  NODE_ENV:        "production"
  JWT_EXPIRES_IN:  "1h"
  SERVICE_NAME:    "auth-microservice"
  SERVICE_VERSION: "1.0.0"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://alloy.alloy.svc.cluster.local:4317"
  LOKI_HOST:                   "http://loki.loki.svc.cluster.local:3100"
  CORS_ALLOWED_ORIGINS: "https://dash.sxdentrypoint.my.id,https://app.sxdentrypoint.my.id"