# Secret for Auth Microservice

apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secret
  namespace: auth-service
  labels:
    app.kubernetes.io/name:      auth-microservice
    app.kubernetes.io/component: secret
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOmZNRWFiTnpMZ0RUTEBhdXRoLXBvc3RncmVzLWhlYWRsZXNzLmF1dGgtcG9zdGdyZXMuc3ZjLmNsdXN0ZXIubG9jYWw6NTQzMi9hdXRoX2Ri
  JWT_SECRET: Y2VmOTA2YWEyZThhZDA4ZDliN2U1NGQwZmU3NWU5OTY3MDc5MjU1ZDAzNzI0MWIwMTJjODVjMTYyZDBlMTJmZjljYWQwNWQwZDc5OGY0ZjQ2MzdlNjU1NWE5NDYwNGYxMzQyYWQwNjNhMzcwODg3ZDIwYzhmMzc0ZWMyMGJiNGI=
  ADMIN_USERNAME: YWRtaW4=
  ADMIN_PASSWORD: QWRtaW5AMTIzNCEK